### ISSUE TITLE
opening a pdf

### ISSUE THREAD

**Issue by interactivevalues** [mozilla/chromeless#112]
when opening a pdf with window.open a new window opens but throws an error:

XML Parsing Error: undefined entity 
Location: chrome://mozapps/content/downloads/unknownContentType.xul 
Line Number 30, Column 18:    <description>&intro.label;</description>

**Comment by nicksanders** [comment]
This happens with csv as well.

Is there any way to tell chromeless to open links it can't render in an external viewer?

**Comment by apoole7** [comment]
It also looks like if trying to download\open files from a javascript managed link within an iframe a different error occurs:

info: navigation blocked for: about:blank
info: navigation blocked for: http://somesite.net/files/apdf.pdf

As nicksanders commented, would an alternative be that; rather than chromeless failing it should be passed to the OS to decide whether to open the given file if it failed the permissible mimetypes check?

**Comment by okyame** [comment]
Hello,
Have you find a solution to open PDF?
thanks

**Comment by nicksanders** [comment]
Hi,

No, although I haven't looked recently to see if anything has changed

Nick

**Comment by okyame** [comment]
what about pdf.js?
who try it?

**Comment by okyame** [comment]
It seems that the bug come from xulrunner

**Comment by ghost** [comment]
Still getting this issue when I try to download any file. I think that chromeless' xulrunner tries to display any linked file instead of downloading unknown formats. 

The only thing I found about this topic is this small segment on the xulrunner wiki: <a href="https://developer.mozilla.org/en/XULRunner_tips#Preferences_needed_for_file_download_dialogs"> link</a>
I didn't manage to solve the problem though.

I hope someone get's it right.
