### ISSUE TITLE
API - require("browser-controls")

### ISSUE THREAD

**Issue by taboca** [mozilla/chromeless#23]
HTML developer needs API control back, forward, reload and top. This relates to the discussion about the use of iframe or other browser implementaion that is available in the HTML, we need to make sure, in case of using iframes, we can go further to do things such as preventing a page load.

**Comment by lloyd** [comment]
should this be exposed as a commonjs module?

Can't the parent HTML page just set the .src of the iframe object in order to send it to a different location?  

Specifically, I'm thinking the parent can expose a button that has an event handler capable of resetting the .src of the child iframe.  That handler could interact with the history module (described in issue #24)

**Comment by taboca** [comment]
Maybe eventually we can remove the CommonJS or under XPCom and make it in the DOM, but first we need to be able to do things like stop loading.

**Comment by lloyd** [comment]
stop loading is a good case.
