### ISSUE TITLE
find a better way to include startup javascript

### ISSUE THREAD

**Issue by lloyd** [mozilla/chromeless#28]
currently we have a main.xul file whose only job is to include some javascript (harness.js).  This xul file specifies a top level window, which is more that what we want.  Ideally we would replace this file with the minimal amount of work required to get our bootstrap javascript executed.

The core issue here is that unlike other xulrunner applications, we want to control app startup programatically (via js), rather than declaratively (via xul).

**Comment by taboca** [comment]
One other angle to see this is not in the programatically versus declaratively. We could offer a declarative initial start point, but I do think, one other related aspect is that, with the main.xul we were launching an initial window and asking XULRunner to launch a window, via the preference: 

pref("toolkit.defaultChromeURI", "chrome://chromeless/content/main.xul");

The issue is solved now due to Lloyd's patch db57ae5f6d4dae75762ab3e0bff2b55fa82b99ed which relates to bugzilla Atuls' patch 
 https://bugzilla.mozilla.org/show_bug.cgi?id=593493

Thanks Lloyd and Atul

**Comment by taboca** [comment]
Additional benefit of the above patch is that we can remove the, now unecessary, pref line cada1059a6cf575eeb9b3cf613a58269a4b72817
