### ISSUE TITLE
inline markup is shown in iframe

### ISSUE THREAD

**Issue by taboca** [mozilla/chromeless#47]
Before I could only see this with gmail, but now I also see in the standard google search results page, at the very end. Our iframes are showing inline markup. Any ideas please help.

**Comment by lloyd** [comment]
Seems like this is related to noscript tags, see sample code I committed in 91394aed900ea8e88fd5a31d9e24c35c4a95e332

I think we should take a peek into firefox to see how this is handled there and why it's not taken care of inside gecko itself...

**Comment by benfrancis** [comment]
I'm wondering if this is the same bug I'm seeing - noscript tags from resources contained in an iFrame are being printed to the screen as plain text and it appears CSS is spilling into iFrames from the Chromeless interface elements outside because CSS doesn't look right on many web sites.

Also, I don't know if this is related but when I'm logged into my Google Account apps like GMail and Google Calendar I just get an about:blank page. The only symptom manifesting itself in the console is an uncaught 'window.external is undefined' exception.

**Comment by taboca** [comment]
@hippygeek the blank page is related to this [1] x-frame-options header. 

http://gecko.mgalli.com/x-frame-options-discussion-follow-up

**Comment by lloyd** [comment]
fixed back in jan with move back to embedded xulrunner browser: f6ec4b721ebeec048a1b21acffa15fa082339ac4

**Comment by viktorkelemen** [comment]
hi, maybe i missed something but could not figure out from the blog post what the solution is for the gmail blank page problem.
thx, V

**Comment by benfrancis** [comment]
@yikulju: I don't think the GMail Blank Page problem is really solved, see issue 33 (https://github.com/mozilla/chromeless/issues/33)

There's also a related problem with iGoogle and Google Calendar where they take over the whole screen!

@taboca has pointed out that if you open GMail in a new window it will work because it's a full browser element rather than just an iFrame, but the problem hasn't been solved for iFrames. He also has a blog post about a possible way of getting a full browser element into Chromeless http://gecko.mgalli.com/html-canvas-that-becomes-a-browser-element but I think the discussion is ongoing
