### ISSUE TITLE
Need a way to get the favicon for a loaded web site

### ISSUE THREAD

**Issue by benfrancis** [mozilla/chromeless#51]
It would be nice to have a helper function to get the favicon for a resource being loaded inside an iFrame.

If there's already a way to achieve this then please do let me know!

**Comment by taboca** [comment]
This also blocks our browser prototype requirements, thanks.

**Comment by lloyd** [comment]
implement a favicon library and test.  docs at http://mozilla.github.com/chromeless/#module/chromeless-kit/favicon/fetch Closed by 9e7e62094daa0e205a38b4475e02a8684c493524.

**Comment by benfrancis** [comment]
Wow, that's a pretty impressive turnaround, thanks. I've just implemented the favicon feature in my project using this library :)

**Comment by lloyd** [comment]
neato! holler if you have any issues with the lib!

**Comment by taboca** [comment]
This is fetching favicon using library is a application style solution. Another approach, which is the thing I was investigating, is a total different direction and refers to proposition to the event model that we have in chromeless to "boost" iframe in order to make them good for writing browser applications. 

The model would be to be smart at DOMLinkAdded, and to be able to call a developer's handler so to notify developer's HTML when iframe content's favicon is ready.  Just leaving the annotation here as it was the direction I was looking.

**Comment by lloyd** [comment]
I think your approach is good.  My assumption is that gecko automatically fetches favicons post page load.  If that is so, we could fire another event at that point.  This would allow the browser code to better optimize network traffic.

We should investigate gecko guts a bit more to see how favicons fetchery functions...

I took the approach I did because I figured that having a library that can fetch favicons even if the page isn't being rendered could be useful in it's own right... And it was a quick way to get there.

I will say tho that js rep of bin data in strings confuses the snot out of me :)
