### ISSUE TITLE
Ability to run apps with full system privileges configurable via appinfo.json

### ISSUE THREAD

**Issue by taboca** [mozilla/chromeless#68]
I constantly have cases I want to write apps with full system privileges. Found one case from a developer: 

Case: 

"i am trying to access and modify webpage content loaded in iframe, but it seems that i can not"

Code: 

http://codepad.org/S5f9QhS0

**Comment by taboca** [comment]
Response to rndbit, current workaround, proposal for fix ( video demo recorded with Chromeless + Ace + Rainbow CAR ) 

http://dl.dropbox.com/u/20061784/rainbow-rnbit-iframe-dom.ogg

**Comment by ghost** [comment]
thank you for the help, however it does not seem to work. this change introduced another issue - jquery is not picked up any more. in order to use jquery in browser code i had to copy jquery code into index.html. As said in ChromelessLoadStop event i can not access  content of iframe, neither can i execute navigate() function (first browser example). Setting url to the url bar works tho.

**Comment by taboca** [comment]
Patch proposal here: 

https://github.com/mozilla/chromeless/commit/c5d0ff5414ae920fb8017efa6a17e596e93e0086

Somehow it works for me. And I also proposed the new property to appinfo module. e

enableSystemPrivilege: true to have it do special things such as: 
- Access to inner iframes
- Ability to do things like drawWindow with the current window
- And all sorts of chrome-level things that we normally would need to ask extended permissions. 

If this looks okay I will check into master.

**Comment by taboca** [comment]
Landed sha: 6d8791d92f671a831360b5f708c6724e033a340b

**Comment by taboca** [comment]
Tests sha: 8bfcc8144829f85e5bd53d1349167e91d5289026

**Comment by taboca** [comment]
Refixed this.
