### ISSUE TITLE
window.open() and target="_*" should dispatch events

### ISSUE THREAD

**Issue by davidmurdoch** [mozilla/chromeless#73]
facebook.com's external links have "target=_blank". Clicking these links from within a Chromeless browser  does nothing at all and the application has no way to know it is supposed to open another URL.

There could be events dispatched named Chromeless_DOMWindowOpenRequest and Chromeless_DOMTabOpenRequest - or something like that.

**Comment by davidmurdoch** [comment]
Also links with `target="_top"` will open in the top frame...the application's index.html.

**Comment by taboca** [comment]
This is amzing request and feature we can do. Yes, as you say, a callback approach right? So developer can decide what to do, pass through popup controls filters, decide to open windows or inline iframes etc.

**Comment by davidmurdoch** [comment]
taboca, and idea how to at least get `target="\_top"` to work correctly. Right now links with `target="\_top"` will replace our "browser" ui. I'll gladly write the code for this if you point me in the right direction.

**Comment by CoderPuppy** [comment]
Working on the _blank and fixed _top.

**Comment by CoderPuppy** [comment]
Got blank callback in my [fork.](http://github.com/drewyoung1/chromeless/)

**Comment by davidmurdoch** [comment]
relevant: https://github.com/mozilla/chromeless/issues/83#issuecomment-1297965

**Comment by lloyd** [comment]
Now that we've merged the content policy implemented by @davidmurdoch, this issue is a ton more tractable.  Have a look at the code: 

https://github.com/mozilla/chromeless/blob/042489d4f959b9fc30ab764677df7240a46f9608/modules/internal/prevent-navigation.js#L71-78

aContext tells us who the requesting nsiDOMWindow is.  aContentLocation tells us what is being requested.  The task now becomes to hook this knowledge into the web-content module so we can also expose events.  It would also be nice to log these navigation events when they occur to make it more discoverable to developers that they can intercept and react to them.

**Comment by davidmurdoch** [comment]
+1
