### ISSUE TITLE
chrome event listeners broken on iframe

### ISSUE THREAD

**Issue by sbeckeriv** [mozilla/chromeless#98]
With the current master event listeners do not fire. I am using the thumbnail example provided. ChromelessDOMSetup and ChromelessLoadStop are not working. In my own code (build off of the thumbnail example) ChromelessLoadProgress is not firing.

**Comment by taboca** [comment]
Due to changes in Gecko infra-structure ( XULRunner 2 is now used ) our older DOM-based events solution fails. This has to do with security restrictions. The require("web-content") is now in place to help out, but I also made some changes to the demo,  sha: 7fea240e450e3f0f1155ed8f0cc980dc074c7f5a based on your comments, and kept the DOM way of doing, it's in the source, please check. And after this commit there is also another update to the sample ( thumbnails ) that has the close button for a given browser ( iframe ). Let me know.

**Comment by sbeckeriv** [comment]
Thanks! the thumbnail example is working again. From that I can adapt my code. I will also read up on web-content
